# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 652a44c1041a57ee5190a91e4d3d415c9f2882dfc7c4c768fb4473bab47474c6829f2a00a5cc07d620570d9610f5724e8f697b556d8b64872871b16a6b6c0bf6

test:
  secret_key_base: dc09c3dd0463f341a89de23ad7480d9be4dfd6b8f5042c95bebb2c382c89c653db4fdc1766efc5c576444c03044c182c89bf96dc115c8ab7c9ebbf31da2d5ac5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
